use alloc::boxed::Box;
use core::sync::atomic::{AtomicU64, Ordering};
use core::task::{Context, Poll};
use core::{future::Future, pin::Pin};

pub mod executor;
pub mod keyboard;
pub mod simple_executor;

pub struct Task {
    /// Unique task ID.
    ///
    /// It is pushed into the task queue by the `TaskWaker` and removed from the queue by the `Executor`.
    id: TaskId,
    /// We store `Future` as a pinned `Box`, preventing it from being moved in memory and invalidating pointers
    /// to the self-referential structures of the state machine generated by the compiler in async functions.
    future: Pin<Box<dyn Future<Output = ()>>>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
struct TaskId(u64);

impl TaskId {
    fn new() -> Self {
        static NEXT_ID: AtomicU64 = AtomicU64::new(0);
        // The `Relaxed` ordering prevents the `fetch_add` instruction from being reordered in the instruction stream.
        // It's the weakest ordering available; we only need it to maintain a unique ID in a parallel environment.
        TaskId(NEXT_ID.fetch_add(1, Ordering::Relaxed))
    }
}

/// Each future is a task.
impl Task {
    /// Create a new task.
    ///
    /// Because `Task` must be maintained indefinitely, we use the lifetime `'static` property on `Task`.
    pub fn new(future: impl Future<Output = ()> + 'static) -> Task {
        Task {
            id: TaskId::new(),
            future: Box::pin(future),
        }
    }

    fn poll(&mut self, context: &mut Context) -> Poll<()> {
        self.future.as_mut().poll(context)
    }
}
