name: CI

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      - name: Install QEMU
        run: |
          sudo apt-get update
          sudo apt-get install qemu-system-x86
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2025-06-13
          profile: minimal
      - name: Install Rustup Components
        run: rustup component add rust-src llvm-tools-preview
      - name: Install bootimage
        run: cargo install bootimage
      - name: Install dependencies
        run: cargo build
      - name: Run tests
        run: cargo test              
